package edu.br.unifacear.webdev2019.usuario.entity;


public enum Permissao  {

	GERENCIAR_VOO,
	GERENCIAR_AEROPORTO,
	GERENCIAR_PARADA,
	GERENCIAR_USUARIO,
	GERENCIAR_TIPO_PERFIL,
	GERENCIAR_AERONAVE,
	GERENCIAR_FABRICANTE,
	GERENCIAR_LOCAL_CHECKIN,
	GERENCIAR_PRIMEIRO_CHECKIN,
	GERENCIAR_SEGUNDO_CHECKIN,
	GERENCIAR_CHECKOUT,
	GERENCIAR_RESERVA;
}
